name: ArticlesApp CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Run linting
    - name: Run pylint
      run: |
        pip install pylint
        python -m pylint app.py --fail-under=7
    
    # Step 5: Run unit tests
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
    
    # Step 6: Run custom quality script
    - name: Run quality script
      run: |
        chmod +x scripts/quality_check.py  # If you created this
        python scripts/quality_check.py
    
    # Step 7: Upload test results (optional)
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test-reports/
          coverage.xml

  build-and-test:
    runs-on: ubuntu-latest
    needs: quality-checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and test
      run: |
        echo "Build and additional tests..."
        # Add your build commands here